export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const ARTICLE_CREATED = "ARTICLE_CREATED";
export const TITLES_FETCHED = "TITLES_FETCHED";
export const SINGLE_ARTICLE_FETCHED = "SINGLE_ARTICLE_FETCHED";
